version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: bayiot_mqtt
    ports:
      - "8883:8883"
    networks:
      saas:
        ipv4_address: 11.0.1.37
    volumes:
      - /etc/bayiot/mosquitto/config:/mosquitto/config
      - /etc/bayiot/mosquitto/data:/mosquitto/data
      - /etc/bayiot/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: bayiot_nodered
    ports:
      - "1880:1880"
    networks:
      saas:
        ipv4_address: 11.0.1.38
    volumes:
      - /etc/bayiot/nodered:/data
    #depends_on:
    #  - mqtt
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: bayiot_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sp0ng3B0B@Umicore
      MYSQL_DATABASE: BayIot
      MYSQL_USER: BayIot
      MYSQL_PASSWORD: Sp0ng3B0B@Umicore
    networks:
      saas:
        ipv4_address: 11.0.1.36  
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3206:3306"

  grafana:
    image: grafana/grafana:latest
    container_name: bayiot_grafana
    ports:
      - "3200:3000"
    networks:
      saas:
        ipv4_address: 11.0.1.39       
    volumes:
      - /etc/bayiot/grafana:/var/lib/grafana
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: bayiot_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your_very_secure_secret
      - JWT_REFRESH_SECRET=your_very_secure_refresh_secret  
    networks:
      saas:
        ipv4_address: 11.0.1.40
    volumes:
      - images_data:/app/public/images
    depends_on:
      - mysql

  nginx:
    container_name: bayiot_dashboard
    build:
      context: .
      dockerfile: nginx/Dockerfile        
    restart: unless-stopped
    volumes:
      - images_data:/usr/share/nginx/html/images
    ports:
      - "8080:80"
    networks:
      saas:
        ipv4_address: 11.0.1.41
    depends_on:
      - backend

volumes:
  images_data:

networks:
  saas:
    external: true 
